export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'

export const GET_ALL_PETS = 'GET_ALL_PETS'
export const GET_ONE_PET = 'GET_ONE_PET'
export const ADD_PET = 'ADD_PET'
export const EDIT_PET = 'EDIT_PET'
export const DELETE_PET = 'DELETE_PET'
export const SEARCH_PET = 'SEARCH_PET'
export const ADOPT_PET = 'ADOPT_PET'
export const SAVE_PET = 'SAVE_PET'
export const UNSAVE_PET = 'UNSAVE_PET'
export const FOSTER_PET = 'UNSAVE_PET'
export const UNFOSTER_PET = 'UNSAVE_PET'
export const GET_ADOPTED_PET = 'GET_ADOPTED_PET'
export const GET_FOSTER_PET = 'GET_FOSTER_PET'
export const GET_SAVED_PET = 'GET_SAVED_PET'
export const ERROR_PETS = 'ERROR_PETS'

